#ifndef FLU_INCBIN_HDR
#define FLU_INCBIN_HDR
#include <climits>
#if defined(__AVX512BW__) || \
    defined(__AVX512CD__) || \
    defined(__AVX512DQ__) || \
    defined(__AVX512ER__) || \
    defined(__AVX512PF__) || \
    defined(__AVX512VL__) || \
    defined(__AVX512F__)
#define FLU_INCBIN_ALIGNMENT_INDEX 6
#elif defined(__AVX__) || defined(__AVX2__)
#define FLU_INCBIN_ALIGNMENT_INDEX 5
#elif defined(__SSE__) || defined(__SSE2__) || defined(__SSE3__) || defined(__SSSE3__) || defined(__SSE4_1__) || defined(__SSE4_2__) || defined(__neon__)
#define FLU_INCBIN_ALIGNMENT_INDEX 4
#elif ULONG_MAX != 0xffffffffu
#define FLU_INCBIN_ALIGNMENT_INDEX 3
#else
#define FLU_INCBIN_ALIGNMENT_INDEX 2
#endif

#define FLU_INCBIN_ALIGN_SHIFT_0 1
#define FLU_INCBIN_ALIGN_SHIFT_1 2
#define FLU_INCBIN_ALIGN_SHIFT_2 4
#define FLU_INCBIN_ALIGN_SHIFT_3 8
#define FLU_INCBIN_ALIGN_SHIFT_4 16
#define FLU_INCBIN_ALIGN_SHIFT_5 32
#define FLU_INCBIN_ALIGN_SHIFT_6 64

#define FLU_INCBIN_ALIGNMENT \
FLU_INCBIN_CONCATENATE(FLU_INCBIN_CONCATENATE(FLU_INCBIN_ALIGN_SHIFT, _), FLU_INCBIN_ALIGNMENT_INDEX)

#define FLU_INCBIN_STR(X) #X
#define FLU_INCBIN_STRINGIZE(X) FLU_INCBIN_STR(X)
#define FLU_INCBIN_CAT(X, Y) X ## Y
#define FLU_INCBIN_CONCATENATE(X, Y) FLU_INCBIN_CAT(X, Y)
#define FLU_INCBIN_EVAL(X) X
#define FLU_INCBIN_INVOKE(N, ...) FLU_INCBIN_EVAL(N(__VA_ARGS__))

#if defined(__ghs__)
#if (__ghs_asm == 2)
#define FLU_INCBIN_MACRO ".file"
#else
#define FLU_INCBIN_MACRO "\tINCBIN"
#endif
#else
#define FLU_INCBIN_MACRO ".incbin"
#endif

#ifndef _MSC_VER
#define FLU_INCBIN_ALIGN __attribute__((aligned(FLU_INCBIN_ALIGNMENT)))
#else
#define FLU_INCBIN_ALIGN __declspec(align(FLU_INCBIN_ALIGNMENT))
#endif

#if defined(__cplusplus)
#define FLU_INCBIN_EXTERNAL extern "C"
#define FLU_INCBIN_CONST extern const
#else
#define FLU_INCBIN_EXTERNAL extern
#define FLU_INCBIN_CONST const
#endif

#ifndef FLU_INCBIN_OUTPUT_SECTION
#if defined(__APPLE__)
#define FLU_INCBIN_OUTPUT_SECTION ".const_data"
#else
#define FLU_INCBIN_OUTPUT_SECTION ".rodata"
#endif
#endif

#define FLU_INCBIN_SECTION ".section " FLU_INCBIN_OUTPUT_SECTION "\n"
#define FLU_INCBIN_GLOBAL(NAME) ".global " FLU_INCBIN_STRINGIZE(FLU_INCBIN_PREFIX) #NAME "\n"
#define FLU_INCBIN_TYPE(NAME) ".type " FLU_INCBIN_STRINGIZE(FLU_INCBIN_PREFIX) #NAME ", @object\n"

#define FLU_INCBIN_EXTERN(NAME) \
FLU_INCBIN_EXTERNAL const FLU_INCBIN_ALIGN unsigned char \
FLU_INCBIN_CONCATENATE(FLU_INCBIN_PREFIX, NAME) FLU_INCBIN_STYLE_IDENT(DATA)[]; \
FLU_INCBIN_EXTERNAL const FLU_INCBIN_ALIGN unsigned char *const \
FLU_INCBIN_CONCATENATE(FLU_INCBIN_PREFIX, NAME) FLU_INCBIN_STYLE_IDENT(END); \
FLU_INCBIN_EXTERNAL const unsigned int \
FLU_INCBIN_CONCATENATE(FLU_INCBIN_PREFIX, NAME) FLU_INCBIN_STYLE_IDENT(SIZE)

#ifdef _MSC_VER
#define FLU_INCBIN(NAME, FILENAME) FLU_INCBIN_EXTERN(NAME)
#else
#define FLU_INCBIN(NAME, FILENAME) \
__asm__(FLU_INCBIN_SECTION \
FLU_INCBIN_GLOBAL_LABELS(NAME, DATA) \
FLU_INCBIN_ALIGN_HOST \
FLU_INCBIN_STRINGIZE(FLU_INCBIN_PREFIX) #NAME FLU_INCBIN_STYLE_STRING(DATA) ":\n" \
FLU_INCBIN_MACRO " \"" FILENAME "\"\n" \
FLU_INCBIN_GLOBAL_LABELS(NAME, END) \
FLU_INCBIN_ALIGN_BYTE \
FLU_INCBIN_STRINGIZE(FLU_INCBIN_PREFIX) #NAME FLU_INCBIN_STYLE_STRING(END) ":\n" \
FLU_INCBIN_BYTE "1\n" \
FLU_INCBIN_GLOBAL_LABELS(NAME, SIZE) \
FLU_INCBIN_ALIGN_HOST \
FLU_INCBIN_STRINGIZE(FLU_INCBIN_PREFIX) #NAME FLU_INCBIN_STYLE_STRING(SIZE) ":\n" \
FLU_INCBIN_INT FLU_INCBIN_STRINGIZE(FLU_INCBIN_PREFIX) #NAME FLU_INCBIN_STYLE_STRING(END) " - " \
FLU_INCBIN_STRINGIZE(FLU_INCBIN_PREFIX) #NAME FLU_INCBIN_STYLE_STRING(DATA) "\n" \
FLU_INCBIN_ALIGN_HOST \
".text\n" \
); \
FLU_INCBIN_EXTERN(NAME)
#endif
#endif
